Assignments/number functions
bhs-intro-to-programming/lashlockbhs pull request #1
Opened 2022-09-09 21:35 UTC by lashlockbhs

2022-09-09 23:34 UTC, gigamonkey requested changes
Please update the function definition syntax and then tag me by mentioning my handle `@gigamonkey` in a comment so I can take another look.

2022-09-09 23:34 UTC, gigamonkey commented on assignments/number-functions/code.js
> +  return Math.abs(x1 - x2) + Math.abs(y1 - y2)
To be even more stylish you could have written this to use the `distance` function you just defined.

```suggestion
  return distance(x1, x2) + distance(y1, y2);
```

Makes it slightly easier to read, say for someone who doesn't necessarily know what Manhattan Distance is.

2022-09-09 23:34 UTC, gigamonkey commented on assignments/number-functions/code.js
> +function add(x, y){
Please convert all these to the function definition syntax I'm teaching you. As I said in class, this syntax is fine though it's somewhat out of fashion for various subtle reasons, some of which I care about.

2022-09-09 23:34 UTC, gigamonkey commented on assignments/number-functions/code.js
> +  return x+y
Statements like this should end with a `;`. I'll talk more about this later but Javascript is kinda loose with when it really requires `;`s but it's good practice to put them in.

2022-09-16 16:20 UTC, lashlockbhs commented on assignments/number-functions/code.js
> +  return x+y
Will do

2022-09-16 16:20 UTC, merged