Assignments/images challenge
bhs-intro-to-programming/lashlockbhs pull request #3
Opened 2022-09-24 18:05 UTC by lashlockbhs

2022-09-27 00:39 UTC, gigamonkey requested changes
Looks good. Left some comments of things you should clean up to make this a bit more idiomatic and therefore easier to understand. And obviously you need to finish `squareOfCircles`.

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  const inc = width/num/2
Whoops. You assumed the width would always be the smaller dimension and then I updated the website so that wasn't necessarily true. Can you make this more robust to that kind of change?

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for(let linesD = 0; linesD!=num; linesD++){
You should run the auto formatter in the editor on all your code to fix a bunch of small formatting issues around the use of whitespace.

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  for (let i = 0; num>i; i++){
While mathematically equivalent, almost all programmers would write that is `i < num` rather than `num > i`. It's important to write idiomatic code so other people can read it easily.

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  const size = width/num
This also suffers from the assumption that `width` is the smaller dimension.

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +      drawCircle(offsetx + r + d*i, offsety + y, r, color)
I like how you compute the x value using `i`. Can you do the same to compute the `y` value using `a` rather than having the separate `y` variable that you have to increment below?

2022-09-27 00:39 UTC, gigamonkey commented on assignments/images-challenge/code.js
> +  let y = r;
Same comment about not really needing this variable as in the previous function.

2022-10-03 21:59 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +  const inc = width/num/2
fixed

2022-10-03 21:59 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +  for(let linesD = 0; linesD!=num; linesD++){
ok will do

2022-10-03 22:00 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +  for (let i = 0; num>i; i++){
ok got it

2022-10-03 22:04 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +  const size = width/num
fixed

2022-10-03 22:25 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +      drawCircle(offsetx + r + d*i, offsety + y, r, color)
fixed on all

2022-10-03 22:28 UTC, lashlockbhs commented on assignments/images-challenge/code.js
> +  let y = r;
fixed

2022-10-04 01:12 UTC, gigamonkey requested changes
Overall pretty good. Left a few comments about small bugs. And I'll challenge you to simplify `squareOfCirles` and fix `checkerBoard`

2023-01-03 23:11 UTC, merged