Assignments/simple draw
bhs-intro-to-programming/lashlockbhs pull request #4
Opened 2022-09-28 21:39 UTC by lashlockbhs

2022-09-29 02:56 UTC, gigamonkey requested changes
I'm not sure if you're done with this or not since you technically haven't requested review yet but if you are, a good habit to get into is to clean up your code before you ask for review. In this case that would mean deleting all the irrelevant commented out code. It's all in version control if you ever need to get it back but you want to present your reviewer with just the code they actually need to review.

2022-09-29 03:47 UTC, lashlockbhs commented
I need to clean it up which I will work on.

2022-09-30 04:34 UTC, gigamonkey approved these changes
Nothing you have to change since this was your own side quest. Left a couple comments about things that I think would make the code a bit more clear. Might as well go ahead and Merge this to close out the PR.

2022-09-30 04:34 UTC, gigamonkey commented on assignments/simple-draw/code.js
> +  return [z_sqr(z[0], z[1])[0] + c[0], z_sqr(z[0], z[1])[1] + c[1]]
This could be a bit more clear with a variable to show that the complex expression `z_sqr(z[0], z[1])` occurs in two places without having to bushwhack through a thicket of `[]`s, `0`s, and `1`s.

E.g.

```javascript
  const zSquared = z_sqr(z[0], z[1]);
  return [zSquared[0] + c[0], zSquared[1] + c[1]];
```

Also saves a tiny bit of compute time since you don't compute the same value twice.

2022-09-30 04:34 UTC, gigamonkey commented on assignments/simple-draw/code.js
> +  if(z[0]>2||z[1]>2){
Not sure I get what this is for. Seem sus to me.

2022-09-30 04:34 UTC, gigamonkey commented on assignments/simple-draw/code.js
> +      let pixelinset = isPixelInSet([xm, ym], iterations)
This can be a `const`.

2022-09-30 04:34 UTC, gigamonkey commented on assignments/simple-draw/code.js
> +  let xm;
Seems like `xm` and `ym` are only used inside the body of the inner `for` loop so you should declare them there. When you declare them out here that makes the reader think they are used more widely than they actually are.

2022-09-30 04:34 UTC, gigamonkey commented on assignments/simple-draw/code.js
> +      xm=(-2-(ofx/bx))/zoom+((4/zoom)/bx)*x
Per the earlier comment about declaring these here, get rid of the earlier `let xm;` and `let ym;` and put a `const` in front of each of these here, I think.

2022-09-30 18:27 UTC, lashlockbhs commented on assignments/simple-draw/code.js
> +  if(z[0]>2||z[1]>2){
Just some old code that I forgot to remove.

2022-09-30 18:28 UTC, lashlockbhs commented on assignments/simple-draw/code.js
> +      xm=(-2-(ofx/bx))/zoom+((4/zoom)/bx)*x
Fixed everything, should I ship it?

2022-10-01 22:26 UTC, gigamonkey approved these changes
Looks good.

2022-10-03 21:52 UTC, merged